In [ ]:
# To study functions of Linear Algebra

In [1]:
!pip install scipy

In [2]:
import scipy
import numpy as np

In [13]:
# Create a Matrix
A = np.mat('[1 2 8;3 4 6;7 8 3;3 7 4]')
A

matrix([[1, 2, 8],
        [3, 4, 6],
        [7, 8, 3],
        [3, 7, 4]])

In [14]:
# To find the transpose of a matrix
A.T

matrix([[1, 3, 7, 3],
        [2, 4, 8, 7],
        [8, 6, 3, 4]])

In [23]:
b = np.mat('[5 ; 6 ; 7]')
b

matrix([[5],
        [6],
        [7]])

In [24]:
# To multiply two matrices, numner of columns should be equal to number of rows.
A*b

matrix([[ 73],
        [ 81],
        [104],
        [ 85]])

In [25]:
help(scipy)

Help on package scipy:

NAME
    scipy

DESCRIPTION
    SciPy: A scientific computing package for Python
    
    Documentation is available in the docstrings and
    online at https://docs.scipy.org.
    
    Contents
    --------
    SciPy imports all the functions from the NumPy namespace, and in
    addition provides:
    
    Subpackages
    -----------
    Using any of these subpackages requires an explicit import. For example,
    ``import scipy.cluster``.
    
    ::
    
     cluster                      --- Vector Quantization / Kmeans
     constants                    --- Physical and mathematical constants and units
     datasets                     --- Dataset methods
     fft                          --- Discrete Fourier transforms
     fftpack                      --- Legacy discrete Fourier transforms
     integrate                    --- Integration routines
     interpolate                  --- Interpolation Tools
     io                           --- Data input and o

In [35]:
b = np.array([5,6,8]) #1D array
b

array([5, 6, 8])

In [36]:
b.shape

(3,)

In [37]:
# To multiply two matrices, numner of columns should be equal to number of rows.
A.dot(b)

matrix([[ 81,  87, 107,  89]])

In [38]:
from scipy import linalg
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [39]:
# # To calculate inverse of a matrix
linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [45]:
# To define array instead of a matrix
b=np.array([[3,4,5],[4,7,8],[5,7,6]])
b

array([[3, 4, 5],
       [4, 7, 8],
       [5, 7, 6]])

In [46]:
# To find inverse of a matrix
linalg.inv(b)

array([[ 1.07692308, -0.84615385,  0.23076923],
       [-1.23076923,  0.53846154,  0.30769231],
       [ 0.53846154,  0.07692308, -0.38461538]])