In [ ]:
# Solving a linear system

In [ ]:
# x +3y + 5z =10
# 2x + 5y +z = 8
# 2x + 3y+ 8z = 3

In [16]:
!pip install scipy

In [22]:
import scipy
import numpy  as np
from scipy import linalg

In [18]:
a= np.array([[1,3,5],[2,5,1],[2,3,8]])
a

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [19]:
b= np.array([[10],[8],[3]])
b

array([[10],
       [ 8],
       [ 3]])

In [20]:
b.shape

(3, 1)

In [23]:
# inversing the array and finding the dot product
linalg.inv(a).dot(b)

array([[-9.28],
       [ 5.16],
       [ 0.76]])